// Generated by CodiumAI

import { describe, expect, it } from "vitest";
import isBrave from ".";
import { BrowserType } from "../../types";

describe('isBrave', () => {

    // Tests that isBrave returns true when given BrowserType.Arc
    it('should return true when given BrowserType.Brave', () => {
      expect(isBrave(BrowserType.Brave)).toBe(true);
    });

    // Tests that isBrave returns false when given any other BrowserType
    it('should return false when given any other BrowserType', () => {
      expect(isBrave(BrowserType.Arc)).toBe(false);
      expect(isBrave(BrowserType.Browser)).toBe(false);
      expect(isBrave(BrowserType.Chrome)).toBe(false);
      expect(isBrave(BrowserType.Edge)).toBe(false);
      expect(isBrave(BrowserType.Firefox)).toBe(false);
      expect(isBrave(BrowserType.Opera)).toBe(false);
      expect(isBrave(BrowserType.Safari)).toBe(false);
    });

    // Tests that isBrave returns false when given undefined
    it('should return false when given undefined', () => {
      expect(isBrave(undefined as unknown as BrowserType)).toBe(false);
    });

    // Tests that isBrave returns false when given null
    it('should return false when given null', () => {
      expect(isBrave(null as unknown as BrowserType)).toBe(false);
    });

    // Tests that isBrave returns false when given a non-BrowserType value
    it('should return false when given a non-BrowserType value', () => {
      expect(isBrave('Arc' as BrowserType)).toBe(false);
      expect(isBrave(123 as unknown as BrowserType)).toBe(false);
      expect(isBrave(true as unknown as BrowserType)).toBe(false);
      expect(isBrave({} as unknown as BrowserType)).toBe(false);
      expect(isBrave([] as unknown as BrowserType)).toBe(false);
    });
});
