// Generated by CodiumAI

import { describe, expect, it } from "vitest";
import isArc from ".";
import { BrowserType } from "../../types";

describe('isArc', () => {

    // Tests that isArc returns true when given BrowserType.Arc
    it('should return true when given BrowserType.Arc', () => {
      expect(isArc(BrowserType.Arc)).toBe(true);
    });

    // Tests that isArc returns false when given any other BrowserType
    it('should return false when given any other BrowserType', () => {
      expect(isArc(BrowserType.Brave)).toBe(false);
      expect(isArc(BrowserType.Browser)).toBe(false);
      expect(isArc(BrowserType.Chrome)).toBe(false);
      expect(isArc(BrowserType.Edge)).toBe(false);
      expect(isArc(BrowserType.Firefox)).toBe(false);
      expect(isArc(BrowserType.Opera)).toBe(false);
      expect(isArc(BrowserType.Safari)).toBe(false);
    });

    // Tests that isArc returns false when given undefined
    it('should return false when given undefined', () => {
      expect(isArc(undefined as unknown as BrowserType)).toBe(false);
    });

    // Tests that isArc returns false when given null
    it('should return false when given null', () => {
      expect(isArc(null as unknown as BrowserType)).toBe(false);
    });

    // Tests that isArc returns false when given a non-BrowserType value
    it('should return false when given a non-BrowserType value', () => {
      expect(isArc('Brave' as BrowserType)).toBe(false);
      expect(isArc(123 as unknown as BrowserType)).toBe(false);
      expect(isArc(true as unknown as BrowserType)).toBe(false);
      expect(isArc({} as unknown as BrowserType)).toBe(false);
      expect(isArc([] as unknown as BrowserType)).toBe(false);
    });
});
